# Generated by Django 3.2.13 on 2022-07-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'aaa'), ('b', 'bbb')], max_length=1)),
                ('comment', models.CharField(choices=[('a', 'abvgd'), ('e', 'eprst')], max_length=1)),
            ],
        ),
    ]
