# Generated by Django 3.2.13 on 2022-07-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='comment',
            new_name='comment2',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='name',
            new_name='name2',
        ),
    ]
