# Generated by Django 3.2.13 on 2022-07-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='autor_of_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.autor'),
        ),
    ]
